name: Node CI

on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - name: Add artifact to github
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist

  npm-publish:
    needs: [build]
    name: npm-publish
    runs-on: ubuntu-latest
    # only on master
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - name: Publish if version in package.json change
        uses: springtype-org/github-action-npm-publish@master
        with:
          install_build_packages: true
          project_build_dir: dist
          create_tag: true
          auth_token: ${{ secrets.npm_token }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  gh-pages:
    needs: [ npm-publish ]
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install yarn
        run: npm install -g yarn
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - name: Install dependencies
        run: yarn
      - name: deploy github pages
        run: yarn prepages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # default: public

